name: Atten-Mixer
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.1.19=h06a4308_1
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.14.5=py37h261ae71_0
  - chardet=4.0.0=py37h06a4308_1003
  - cmake=3.19.6=h973ab73_0
  - cryptography=3.4.7=py37hd23ed53_0
  - cudatoolkit=11.0.221=h6bb024c_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - expat=2.3.0=h2531618_2
  - freetype=2.10.4=h5ab3b9f_0
  - future=0.18.2=py37_1
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-include=2020.2=256
  - mkl-service=2.3.0=py37he8ac12f_0
  - mkl_fft=1.3.0=py37h54f3939_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=py37hff7bd54_0
  - numpy=1.19.2=py37h54aff64_0
  - numpy-base=1.19.2=py37hfa32c7d_0
  - olefile=0.46=py_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.1.2=py37he98fc37_0
  - pip=21.0.1=py37h06a4308_0
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py37_1
  - python=3.7.9=h7579374_0
  - pyyaml=5.4.1=py37h27cfd23_1
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rhash=1.4.1=h3c74f83_1
  - setuptools=52.0.0=py37h06a4308_0
  - six=1.15.0=pyhd3eb1b0_0
  - sqlite=3.35.3=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - urllib3=1.26.4=pyhd3eb1b0_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pytorch=1.7.1=py3.7_cuda11.0.221_cudnn8.0.5_0
  - torchaudio=0.7.2=py37
  - torchvision=0.8.2=py37_cu110
  - pip:
    - absl-py==0.12.0
    - aiofiles==0.6.0
    - aiohttp==3.7.4.post0
    - apex==0.1
    - ase==3.21.1
    - async-timeout==3.0.1
    - attrs==20.3.0
    - blessings==1.7
    - blis==0.7.4
    - boto3==1.11.11
    - botocore==1.14.17
    - cached-property==1.5.2
    - cachetools==4.2.1
    - catalogue==2.0.4
    - click==7.1.2
    - colorama==0.4.4
    - colorlog==5.0.1
    - configparser==5.0.2
    - cycler==0.10.0
    - cymem==2.0.5
    - decorator==4.4.2
    - deepspeed==0.3.13
    - dgl==0.4.3.post2
    - dgl-cu111==0.6.1
    - dglke==0.1.2
    - docker-pycreds==0.4.0
    - docutils==0.15.2
    - en-core-web-sm==3.0.0
    - fsspec==0.8.7
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.28.0
    - google-auth-oauthlib==0.4.4
    - googledrivedownloader==0.4
    - gpustat==0.6.0
    - grpcio==1.36.1
    - h5py==3.2.1
    - httptools==0.1.1
    - importlib-metadata==3.10.0
    - iniconfig==1.1.1
    - isodate==0.6.0
    - jieba==0.42.1
    - jinja2==2.11.3
    - jmespath==0.10.0
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - littleutils==0.2.2
    - llvmlite==0.36.0
    - loguru==0.5.3
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.4.1
    - multidict==5.1.0
    - murmurhash==1.0.5
    - networkx==2.5
    - nltk==3.5
    - numba==0.53.1
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - ogb==1.3.1
    - outdated==0.2.1
    - packaging==20.9
    - pandas==1.2.3
    - pathtools==0.1.2
    - pathy==0.5.2
    - pluggy==0.13.1
    - preshed==3.0.5
    - promise==2.3
    - protobuf==3.15.6
    - psutil==5.8.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pydantic==1.7.3
    - pyparsing==2.4.7
    - pytest==6.2.3
    - python-dateutil==2.8.1
    - python-louvain==0.15
    - pytorch-lightning==1.2.6
    - pytz==2021.1
    - rdflib==5.0.0
    - regex==2020.1.8
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.3.6
    - sanic==21.3.2
    - sanic-routing==0.5.2
    - scikit-learn==0.24.1
    - scipy==1.6.2
    - sentencepiece==0.1.95
    - sentry-sdk==1.0.0
    - shortuuid==1.0.1
    - smart-open==3.0.0
    - smmap==4.0.0
    - spacy==3.0.6
    - spacy-legacy==3.0.5
    - srsly==2.4.1
    - subprocess32==3.5.4
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - thinc==8.0.3
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.8.1
    - torch-cluster==1.5.9
    - torch-geometric==1.6.3
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - torch-spline-conv==1.2.1
    - torchmetrics==0.2.0
    - torchtext==0.8.0
    - tqdm==4.59.0
    - typer==0.3.2
    - ujson==4.0.2
    - uvloop==0.15.2
    - wandb==0.10.24
    - wasabi==0.8.2
    - websockets==8.1
    - werkzeug==1.0.1
    - wget==3.2
    - yarl==1.6.3
    - zipp==3.4.1
prefix: /home/peiyan/anaconda3/envs/robust

